executors:
  go_image:
    docker:
      - image: circleci/golang:1.11.5
        environment:
          GO111MODULE: "on"
  node_image:
    docker:
      - image: circleci/node:10.15.0

version: 2.1
jobs:
  go_build:
    working_directory: ~/go/src/github.com/teixy/
    
    executor: go_image
    
    steps:
      - checkout

      - restore_cache:
          name: Restore go modules cache
          keys:
              - v1-mod-{{ .Branch }}-{{ checksum "go/go.mod" }}

      - run:
          name: Vendoring
          command: go mod download
          
      - save_cache:
          name: Save go modules cache
          key: v1-mod-{{ .Branch }}-{{ checksum "go/go.mod" }}
          paths:
              - ~/go/pkg/mod/cache

      - run:
          name: Build go binary
          command: |
              cd go/
              go build -v -o main main.go
              
  support_build:
    working_directory: ~/teixy
    
    executor: node_image
    
    steps:
      - checkout
      
      - restore_cache:
          name: Restore node modules from cache
          keys:
              - v1-yarn-{{ .Branch }}-{{ checksum "frontend/support/yarn.lock" }}
              - v1-node-{{ .Branch }}-{{ checksum "frontend/support/yarn.lock" }}
              
      - run:
          name: Install latest yarn
          command: |
              npm uninstall yarn
              npm install yarn
              
      - run:
          name: Install node modules
          command: |
                cd frontend/support
                yarn install
              
      - save_cache:
          key: v1-yarn-{{ .Branch }}-{{ checksum "frontend/support/yarn.lock" }}
          paths:
              - ~/.cache/yarn
              
      - save_cache:
          key: v1-node-{{ .Branch }}-{{ checksum "frontend/support/package.json" }}
          paths:
              - ~/teixy/frontend/support/node_modules
      
      - run:
          name: yarn build
          command: |
                cd frontend/support
                yarn run build
workflows:
  version: 2.1
  go_build:
    jobs:
      - go_build
  vue_build:
    jobs:
      - support_build
      