version: 2
jobs:
  go_build:
    working_directory: ~/go/src/github.com/teixy/

    docker:
      - image: circleci/golang:1.11.5
        environment:
          GO111MODULE: "on"
    
    steps:
      - checkout

      - restore_cache:
          name: Restore go modules cache
          keys:
              - v1-mod-{{ .Branch }}-{{ checksum "go/go.mod" }}

      - run:
          name: Vendoring
          command: go mod download
          
      - save_cache:
          name: Save go modules cache
          key: v1-mod-{{ .Branch }}-{{ checksum "go/go.mod" }}
          paths:
              - ~/go/pkg/mod/cache

      - run:
          name: Build go binary
          command: |
              cd go/
              go build -v -o main main.go
              
  support_build:
    working_directory: ~/teixy
    
    docker:
      - image: circleci/node:10.15.0
    
    steps:
      - checkout
      
      - run:
          name: install latest yarn
          command: |
              sudo npm uninstall yarn
              sudo npm install yarn -g
      
      - restore_cache:
          name: Restore node modules from cache
          keys:
              - v1-node-{{ .Branch }}-{{ checksum "frontend/support/yarn.lock" }}
            
      - run:
          name: install node modules
          command: |
                cd frontend/support
                yarn install
      
      - save_cache:
          key: v1-node-{{ .Branch }}-{{ checksum "frontend/support/yarn.lock" }}
          paths:
              - ~/teixy/frontend/support/node_modules
      
      - run:
          name: yarn build
          command: |
                cd frontend/support
                yarn run build
workflows:
  version: 2
  go_build:
    jobs:
      - go_build
  vue_build:
    jobs:
      - support_build
      