version: 2
jobs:
  go_build:
    working_directory: ~/go/src/github.com/teixy

    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    
    steps:
      - checkout

      - restore_cache:
          name: Restore go modules cache
          key:
              - v1-mod-{{ .Branch }}-{{ checksum "go/go.mod" }}

      - run:
          name: Vendoring
          command: go mod download
          
      - save_cache:
          name: Save go modules cache
          key: v1-mod-{{ .Branch }}-{{ checksum "go/go.mod" }}
          paths:
              - ~/go/pkg/mod/cache

      - run:
          name: Build go binary
          command: |
              cd go/
              go build -v -o main main.go
              
  support_build:
    working_directory: ~/teixy
    
    docker:
      - image: circleci/node:10.15.0
    
    steps:
      - checkout
      
      - restore_cache:
          name: Restore yarn cache
          key: v1-yarn-{{ .Branch }}-{{ checksum "frontend/support/yarn.lock" }}
          
      - restore_cache:
          name: Restore node modules from cache
          key: v1-node-{{ .Branch }}-{{ checksum "frontend/support/package.json" }}
          
      - run:
          name: Install latest yarn
          command: |
              npm uninstall yarn
              npm install yarn
              
      - run:
          name: Install node modules
          command: |
                cd frontend/support
                yarn install
              
      - save_cache:
          name: Save yarn cache
          key: v1-yarn-{{ .Branch }}-{{ checksum "frontend/support/yarn.lock" }}
          paths:
              - ~/.cache/yarn
              
      - save_cache:
          name: Save node modules cache
          key: v1-node-{{ .Branch }}-{{ checksum "frontend/support/package.json" }}
          paths:
              - ~/teixy/frontend/support/node_modules
      
      - run:
          name: Exec yarn build
          command: |
                cd frontend/support
                yarn run build
                
      - persist_to_workspace:
          root: .
          paths:
            - .
            
  support_deploy_stg:
    working_directory: ~/teixy

    docker:
      - image: circleci/node:8.11.3

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install firebase
          command: |
                cd frontend/support
                npm install --save firebase-tools
      
      - run:
          name: Deploy project
          command: |
                cd frontend/support
                npx firebase deploy --only hosting --project ${FIREBASE_PROJECT_NAME_STG} --token ${FIREBASE_TOKEN_STG}
                
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  support_deploy_production:
    working_directory: ~/teixy

    docker:
      - image: circleci/node:8.11.3

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Deploy project
          command: |
                cd frontend/support
                npx firebase deploy --only hosting --project ${FIREBASE_PROJECT_NAME} --token ${FIREBASE_TOKEN}
            
workflows:
  version: 2
  go_build:
    jobs:
      - go_build
  support:
    jobs:
      - support_build
      - support_deploy_stg:
          context: firebase
          requires:
            - support_build
          filters:
            branches:
              only: develop
      - approve_deploy_production:
          type: approval
          requires:
            - support_deploy_stg
      - support_deploy_production:
          context: firebase
          requires:
            - approve_deploy_production
