CREATE TABLE IF NOT EXISTS `tags` (
  `tag_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name`   CHAR NOT NULL,
  `mtime`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tag_id`)
) ENGINE=INNODB;
